### ISSUE TITLE
wikipii_dataset.ipynb fails collecting page links

### ISSUE THREAD

**Issue by gustavz** [ratmcu/wikipiifed#1]
Hi running the collecting page links cell:
```python
quote_page = 'https://en.wikipedia.org/w/index.php?title=Category:Living_people'
page = urllib.request.urlopen(quote_page)
soup = BeautifulSoup(page, 'html.parser')
links = []
i = 0
while i  < 10:
    content_big = soup.find('div', attrs={'class': 'mw-content-ltr'}) # or infobox biography vcard
    link_list = content_big.find('div', attrs={'class': 'mw-category'}) # or infobox biography vcard
    links.extend(link_list.find_all('a'))
    print(len(links))
    next_page = None
    for j, aa in enumerate(soup.find_all('a')):
        if aa.text == 'next page':
            next_page = aa.get('href')
            if j%100 == 0:
                print(aa.get('href')[:10])
            page = urllib.request.urlopen('https://en.wikipedia.org' + next_page)
            soup = BeautifulSoup(page, 'html.parser')
            break
    if next_page == None:
        break
    i = i + 1
 
links
```
fails with `AttributeError: 'NoneType' object has no attribute 'find_all'` because `link_list` is `None`

Did something change at wikipedia that broke the script?

**Comment by gustavz** [comment]
The following change seems to solve it:
```python
link_list = soup.find('div', attrs={'class': 'mw-category'})
```

**Comment by gustavz** [comment]
Looking closer at the while loop. What is this expected to do? it just duplicates the extracted links 10 times.
Why is this done @ratmcu ?

**Comment by gustavz** [comment]
So after multiple fixes in the notebook it finally fails at cell `creating annotated files from urls` with a multiprocessing error I can't solve:
```
...
workers created
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'do_job' on <module '__main__' (built-in)>
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
...
  File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'do_job' on <module '__main__' (built-in)>
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?e7d5fd40-acf0-43b6-b2e2-fe702a4e1569) or open in a [text editor](command:workbench.action.openLargeOutput?e7d5fd40-acf0-43b6-b2e2-fe702a4e1569). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
workers started
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'do_job' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'save_chunk_to_disk' on <module '__main__' (built-in)>
all input queues drained
13.471699875000922
```

**Comment by ratmcu** [comment]
I am bit out of recollection at the exact reason for this 10x looping, This is due to overcome phantom table contents I guess.

**Comment by ratmcu** [comment]
> So after multiple fixes in the notebook it finally fails at cell `creating annotated files from urls` with a multiprocessing error I can't solve:
> 
> ```
> ...
> workers created
> 0.00s - Debugger warning: It seems that frozen modules are being used, which may
> 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
> 0.00s - to python to disable frozen modules.
> 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
> 0.00s - Debugger warning: It seems that frozen modules are being used, which may
> 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
> 0.00s - to python to disable frozen modules.
> 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
>     self = reduction.pickle.load(from_parent)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: Can't get attribute 'do_job' on <module '__main__' (built-in)>
> 0.00s - Debugger warning: It seems that frozen modules are being used, which may
> 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
> 0.00s - to python to disable frozen modules.
> 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
> ...
>   File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
>     self = reduction.pickle.load(from_parent)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: Can't get attribute 'do_job' on <module '__main__' (built-in)>
> Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?e7d5fd40-acf0-43b6-b2e2-fe702a4e1569) or open in a [text editor](command:workbench.action.openLargeOutput?e7d5fd40-acf0-43b6-b2e2-fe702a4e1569). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
> workers started
> 0.00s - Debugger warning: It seems that frozen modules are being used, which may
> 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
> 0.00s - to python to disable frozen modules.
> 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
> 0.00s - Debugger warning: It seems that frozen modules are being used, which may
> 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
> 0.00s - to python to disable frozen modules.
> 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
>     self = reduction.pickle.load(from_parent)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: Can't get attribute 'do_job' on <module '__main__' (built-in)>
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/gustav.vonzitzewitz/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
>     self = reduction.pickle.load(from_parent)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: Can't get attribute 'save_chunk_to_disk' on <module '__main__' (built-in)>
> all input queues drained
> 13.471699875000922
> ```

regarding this, I believe it can be a version mismatch due to a later python version

**Comment by ratmcu** [comment]
also refer to the abstracted functions imported from this repo: https://github.com/ratmcu/wiki_ner
